# Generated by Django 4.2.30 on 2026-08-21 19:02

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_teachingcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvdocument',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='publications/'),
        ),
        migrations.AlterField(
            model_name='teachingresource',
            name='file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='resources/'),
        ),
    ]
